### ISSUE TITLE
Merge styles

### ISSUE THREAD

**Issue by maltsev** [maltsev/htmlnano#18]
Merge several `<style>` into one. Consider if the style tag's position is significant for rendering.

@stevenvachon, thanks for the idea.

**Comment by stevenvachon** [comment]
Tag's position doesn't affect anything, except perhaps while streaming the page on a very slow connection. CSS is always cascaded, so once the page is loaded, the result is the same as if they were merged.

**Comment by maltsev** [comment]
Actually, it does if [the `scoped` attribute](http://html5doctor.com/the-scoped-attribute/) is present.

**Comment by stevenvachon** [comment]
Aye, didn't know about that

**Comment by maltsev** [comment]
Done. Will be shipped in the next release (0.1.4).
